<?php

declare(strict_types=1);

namespace Marrow\AiContext\Commands;

use Marrow\Application;
use Marrow\Config\Repository as ConfigRepository;
use Marrow\Console\Command;
use Marrow\Module\ModuleManager;
use Marrow\Routing\Router;

/**
 * Writes AGENTS.md at the project root: a live map of this specific app
 * (modules, routes, config) plus static Marrow conventions that aren't
 * obvious from reading any single file — the kind of thing that otherwise
 * costs an agent (or a new contributor) several wrong turns to discover.
 *
 *   php forge ai:context
 *
 * Safe to run repeatedly — it always overwrites the whole file, so the
 * live sections never go stale after a route/module change. Runs in
 * console context after Application::boot(), so modules/routes are
 * already fully registered (including package-auto-discovered ones) by
 * the time this reads them.
 */
class AiContextCommand extends Command
{
    protected string $signature = 'ai:context {--path=AGENTS.md : Output path, relative to the project root}';
    protected string $description = 'Generate AGENTS.md — a live map of this app for AI coding agents';

    public function __construct(
        private readonly Application $app,
        private readonly ModuleManager $modules,
        private readonly Router $router,
        private readonly ConfigRepository $config,
    ) {
        parent::__construct();
    }

    protected function handle(): int
    {
        $path = base_path((string) $this->option('path'));
        $docsPath = $this->frameworkDocsPath();

        $content = $this->buildModulesSection($docsPath)
            . $this->buildRoutesSection()
            . $this->buildConfigSection()
            . $this->buildDocsIndexSection($docsPath)
            . $this->buildConventionsSection($docsPath);

        $header = $this->buildHeader();

        file_put_contents($path, $header . $content);

        $this->success("Written: {$path}");
        if ($docsPath === null) {
            $this->warn('Could not locate the framework\'s docs/ directory (not shipped with this install?) — the documentation index was skipped and conventions below reference generic paths.');
        }
        return self::SUCCESS;
    }

    /**
     * Resolves the installed `marrow/framework` package's own
     * `docs/` directory by reflecting on a framework class's file location
     * — the same technique `BaseModule::path()` uses to make a module
     * portable to `vendor/`. Works identically whether the framework is a
     * real Composer install, a symlinked path-repository, or copied via
     * `COMPOSER_MIRROR_PATH_REPOS=1` — it never assumes a fixed
     * `vendor/marrow/framework` path.
     */
    private function frameworkDocsPath(): ?string
    {
        $frameworkRoot = dirname((new \ReflectionClass(Application::class))->getFileName(), 2);
        $docs = $frameworkRoot . '/docs';

        return is_dir($docs) ? $docs : null;
    }

    /**
     * Renders an absolute path relative to the project root when it's
     * actually inside it (the common case), or leaves it absolute
     * otherwise (a path-repository symlink can legitimately point outside
     * the project directory during local package development).
     */
    private function relativeToBase(string $path): string
    {
        $base = str_replace('\\', '/', rtrim(base_path(), '/\\'));
        $real = str_replace('\\', '/', rtrim($path, '/\\'));

        return str_starts_with($real, $base . '/') ? substr($real, strlen($base) + 1) : $real;
    }

    private function buildHeader(): string
    {
        $date = date('Y-m-d H:i');
        $name = (string) $this->config->get('app.name', 'Marrow app');
        $env = $this->app->environment();
        $version = $this->app->version();

        return <<<MD
# AGENTS.md

> Generated by `php forge ai:context` (marrow/ai-context) on {$date}.
> Read this before exploring the source tree — it's the map, the code is
> the territory. Regenerate after adding/removing a route or module:
> the live sections below go stale otherwise, the conventions don't.

## App

- **Name**: {$name}
- **Environment**: {$env}
- **Marrow version**: {$version}
- **PHP**: {$this->phpVersion()}


MD;
    }

    private function phpVersion(): string
    {
        return PHP_VERSION;
    }

    private function buildModulesSection(?string $docsPath): string
    {
        $meta = $this->modules->getMeta();
        $rows = '';

        foreach ($meta as $class => $attr) {
            $imports = empty($attr->imports) ? '—' : implode(', ', array_map('class_basename', $attr->imports));
            $exports = empty($attr->exports) ? '—' : implode(', ', array_map('class_basename', $attr->exports));
            $commands = empty($attr->commands) ? '—' : implode(', ', array_map('class_basename', $attr->commands));
            $rows .= "| `{$attr->name}` | `{$class}` | {$imports} | {$exports} | {$commands} |\n";
        }

        $count = count($meta);
        $modulesDoc = $docsPath !== null ? $this->relativeToBase($docsPath) . '/modules.md' : 'docs/modules.md';

        return <<<MD
## Enabled modules ({$count})

Every module below is actually registered right now — this includes
modules declared in `config/modules.php` **and** any auto-discovered from
an installed package's `composer.json` (`extra.marrow.modules`; see
`{$modulesDoc}#distributing-a-module-as-a-package`). Don't assume
`config/modules.php` alone lists everything active.

| Name | Class | Imports | Exports | Commands |
|---|---|---|---|---|
{$rows}

MD;
    }

    private function buildRoutesSection(): string
    {
        $rows = '';
        $count = 0;

        foreach ($this->router->getRoutes()->all() as $method => $methodRoutes) {
            foreach ($methodRoutes as $route) {
                $count++;
                $action = $route->getAction();
                $action = is_array($action)
                    ? implode('@', [class_basename($action[0]), $action[1]])
                    : (is_callable($action) ? 'Closure' : (string) $action);
                $mw = implode(', ', $route->getMiddlewares()) ?: '—';
                $name = $route->getName() ?? '—';

                $rows .= "| " . strtoupper($method) . " | `{$route->getUri()}` | `{$name}` | {$action} | {$mw} |\n";
            }
        }

        return <<<MD
## Routes ({$count})

Machine-readable form: `php forge route:list --json`.

| Method | URI | Name | Action | Middleware |
|---|---|---|---|---|
{$rows}

MD;
    }

    private function buildConfigSection(): string
    {
        $files = glob(base_path('config') . '/*.php') ?: [];
        $names = array_map(static fn (string $f) => basename($f), $files);
        sort($names);
        $list = implode(', ', array_map(static fn (string $n) => "`{$n}`", $names));

        return <<<MD
## Config files present

{$list}


MD;
    }

    /**
     * Reads every `.md` file in the framework's own `docs/` directory and
     * indexes it by title + first prose paragraph — extracted from the
     * actual shipped documentation, not a hand-maintained copy that can
     * drift from it. Gives an agent a real table of contents with paths it
     * can open directly, valid whether the framework lives at
     * `vendor/marrow/framework` (a real install) or a
     * symlinked/mirrored path repository (local package development).
     */
    private function buildDocsIndexSection(?string $docsPath): string
    {
        if ($docsPath === null) {
            return '';
        }

        $files = glob($docsPath . '/*.md') ?: [];
        sort($files);

        $relDocs = $this->relativeToBase($docsPath);
        $rows = '';

        foreach ($files as $file) {
            [$title, $summary] = $this->parseDoc($file);
            $rel = $relDocs . '/' . basename($file);
            $rows .= "| [{$title}]({$rel}) | {$summary} |\n";
        }

        return <<<MD
## Framework documentation ({$relDocs}/)

Read straight from disk — these ship inside the installed
`marrow/framework` package itself, so they're always in sync
with the version actually running, never a copy that can drift out of date.

| Doc | Covers |
|---|---|
{$rows}

MD;
    }

    /**
     * Extracts a doc's `# Title` and its first real prose paragraph
     * (skipping headings, code fences, tables, and blockquotes) as a short
     * one-line summary for the index above.
     *
     * @return array{0: string, 1: string}
     */
    private function parseDoc(string $file): array
    {
        $lines = file($file, FILE_IGNORE_NEW_LINES) ?: [];
        $title = basename($file, '.md');
        $titleFound = false;
        $paragraph = [];

        foreach ($lines as $line) {
            $trimmed = trim($line);

            if (!$titleFound) {
                if (str_starts_with($trimmed, '# ')) {
                    $title = trim(substr($trimmed, 2));
                    $titleFound = true;
                }
                continue;
            }

            if ($trimmed === '' || str_starts_with($trimmed, '#') || str_starts_with($trimmed, '```')
                || str_starts_with($trimmed, '|') || str_starts_with($trimmed, '>')) {
                if ($paragraph !== []) {
                    break;
                }
                continue;
            }

            $paragraph[] = $trimmed;
        }

        $summary = trim((string) preg_replace('/`([^`]+)`/', '$1', implode(' ', $paragraph)));
        $summary = str_replace('|', '\\|', $summary);
        if ($summary === '') {
            $summary = '—';
        } elseif (mb_strlen($summary) > 160) {
            $summary = mb_substr($summary, 0, 157) . '…';
        }

        return [$title, $summary];
    }

    private function buildConventionsSection(?string $docsPath): string
    {
        // Static, hand-authored, applies to any Marrow app. `docs/`
        // below is swapped for the real resolved path once built, since a
        // real install serves these from `vendor/...`, not the project root.
        $text = <<<'MD'
## Marrow conventions & gotchas

Read these before making a change — each one cost real debugging time to
discover once.

- **Routing is module-only.** `Migrator`/`ModuleManager` aside, there is no
  global `routes/web.php`. Every route lives in some `modules/{Name}/routes.php`
  (local or package-shipped). A controller generated with `make:controller`
  and no `--module` lands in `app/Controllers/`, but nothing will ever route
  to it — always pass `--module=Name`.
- **A module's files don't have to live under the app's local `modules/`
  directory.** `BaseModule::path()` resolves Views/routes/migrations by
  reflecting on the module class's own file location, so a module shipped
  in a `vendor/` Composer package works identically to a local one. See
  `docs/modules.md#distributing-a-module-as-a-package`.
- **`config('modules.enabled')` is not the full picture.** Auto-discovered
  package modules (`extra.marrow.modules` in a dependency's own
  `composer.json`) are merged in during `Application::boot()`, not written
  back to config. To get the real active list, use `ModuleManager::getModulePaths()`
  or `getMeta()`, not `config('modules.enabled')` directly.
- **Middleware colon-parameters always arrive as strings.**
  `->middleware('throttle:60,1')` passes `'60'` and `'1'` as strings to
  `handle()`, never coerced. A parameter typed as plain `int`/`bool` throws
  a `TypeError` the first time that middleware actually runs — type it
  `string|int` and cast inside the method.
- **A class can't redeclare a trait's property with a different default.**
  PHP treats that as a fatal "incompatible" composition error, not an
  override — assign the value in the constructor instead
  (`$this->prop = array_merge($this->prop, [...]);` after `parent::__construct()`).
- **`db:seed`'s default `--class` is `Database\Seeders\DatabaseSeeder`**
  (matching `make:seeder`'s own non-module namespace convention) — a bare
  seeder generated without a namespace won't be found by plain `db:seed`.
- **`migrate:fresh` needs `--force` for non-interactive use** (CI, scripts)
  — without it, it blocks forever waiting for a confirmation prompt that
  never comes.
- **`Auth\Concerns\Auditable` doesn't wire itself up.** `Model` never calls
  `auditCreated()`/`auditUpdated()`/`auditDeleted()` automatically (there's
  no shipped `Marrow\Events\Model\{Created,Updated,Deleted}` event class
  for `fireEvent()` to dispatch) — override `save()`/`delete()` on the
  model to call them, or the audit table just stays empty.
- **Vite's dev marker file is `public/hot`**, not `public/build/hot` —
  verified against `laravel-vite-plugin` v3 + Vite 8, the combination
  Marrow's own `vite_dev_mode()`/`vite_asset()`/`vite_client()` Twig
  functions are built against.
- **A Tailwind class built from a variable never generates any CSS.**
  `bg-{{ status }}-500` never appears as a complete literal token
  (`bg-emerald-500`, ...) anywhere in the raw `.twig` file, so Tailwind's
  scanner — which does no templating evaluation — never generates it; the
  element silently renders with no color. Keep every candidate class as a
  full literal string somewhere scanned, e.g. a Twig map:
  `{% set dot = {'ok': 'bg-emerald-500', ...} %}` then `{{ dot[status] }}`.
- **Twig `strict_variables` is on whenever `app.debug` is true.** A `null`
  model attribute makes `{% if model.attr %}` throw in debug mode
  (`Model::__isset()` uses `isset()`) — write `{{ model.attr ?? '' }}`,
  not `{{ model.attr ?: '' }}` or a bare `{% if %}`.
- **`#[Column]` on a `Model` is class-level, never property-level.** A
  `Model`'s fields are virtual (stored in an internal array via
  `__get()`/`__set()`) — a real declared property with the same name
  shadows those magic methods entirely, so `$post->title` would silently
  read an uninitialized native property instead of the model's own
  storage. Stack `#[Column('title')]` on the class itself instead.

See `docs/*.md` for the full picture — this section is the "would have
saved time to know up front" shortlist, not a replacement for it.
MD;

        $rel = $docsPath !== null ? $this->relativeToBase($docsPath) : 'docs';

        return str_replace('docs/', $rel . '/', $text);
    }
}
